/**
 * Size budget for the shipped extension.
 *
 * The extension has zero runtime dependencies, so its size is entirely its own
 * source. That makes a budget worth having and easy to keep: any growth is
 * something someone wrote, not something npm pulled in. The failure this
 * catches is not "the zip got big" — it is a dependency, a copied library or a
 * generated file arriving without anyone deciding to ship it.
 *
 *   node scripts/check-size.mjs            check against the budget
 *   node scripts/check-size.mjs --update   rewrite the budget from reality
 *
 * The budget lives in `size-budget.json`, committed, with headroom stated
 * explicitly rather than hidden in a percentage somewhere in this file.
 */

import { readFile, readdir, stat, writeFile } from 'node:fs/promises';
import { join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = resolve(fileURLToPath(new URL('..', import.meta.url)));
const DIST = join(projectRoot, 'dist');
const ZIP = join(projectRoot, 'sf-releaselens.zip');
const BUDGET = join(projectRoot, 'size-budget.json');

/** Excluded from the package, so excluded from the measurement. */
const NOT_SHIPPED = ['.map', '.d.ts', '.tsbuildinfo'];

async function walk(dir, acc = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      await walk(path, acc);
    } else if (!NOT_SHIPPED.some((suffix) => path.endsWith(suffix))) {
      acc.push({ path: relative(DIST, path).split(sep).join('/'), bytes: (await stat(path)).size });
    }
  }
  return acc;
}

async function measure() {
  const files = await walk(DIST);
  const unpackedBytes = files.reduce((total, file) => total + file.bytes, 0);
  const zipBytes = (await stat(ZIP)).size;

  const largest = [...files].sort((a, b) => b.bytes - a.bytes).slice(0, 5);
  return { zipBytes, unpackedBytes, fileCount: files.length, largest, files };
}

function kb(bytes) {
  return `${(bytes / 1024).toFixed(1)} KB`;
}

async function main() {
  const measured = await measure();

  if (process.argv.includes('--update')) {
    const budget = {
      $comment:
        'Generated by `node scripts/check-size.mjs --update`. Limits are the measured size plus the stated headroom, rounded up to the nearest KB. Raise them deliberately, in a commit that says why.',
      headroom: '15% on totals, 25% on any single file',
      measuredAt: new Date().toISOString().slice(0, 10),
      measured: {
        zipBytes: measured.zipBytes,
        unpackedBytes: measured.unpackedBytes,
        fileCount: measured.fileCount,
      },
      limits: {
        zipBytes: roundUpKb(measured.zipBytes * 1.15),
        unpackedBytes: roundUpKb(measured.unpackedBytes * 1.15),
        // A new file is normal; forty new files is a vendored library.
        fileCount: measured.fileCount + 15,
        largestFileBytes: roundUpKb(measured.largest[0].bytes * 1.25),
      },
    };
    await writeFile(BUDGET, `${JSON.stringify(budget, null, 2)}\n`, 'utf8');
    process.stdout.write(`Wrote ${BUDGET}\n`);
    report(measured, budget);
    return;
  }

  const budget = JSON.parse(await readFile(BUDGET, 'utf8'));
  report(measured, budget);

  const failures = [];
  const check = (label, actual, limit, unit = kb) => {
    if (actual > limit) {
      failures.push(
        `${label}: ${unit(actual)} exceeds the budget of ${unit(limit)} ` +
          `(over by ${unit(actual - limit)})`,
      );
    }
  };

  check('Packaged zip', measured.zipBytes, budget.limits.zipBytes);
  check('Unpacked dist/', measured.unpackedBytes, budget.limits.unpackedBytes);
  check('File count', measured.fileCount, budget.limits.fileCount, (n) => `${n} files`);
  check('Largest single file', measured.largest[0].bytes, budget.limits.largestFileBytes);

  if (failures.length > 0) {
    process.stderr.write(
      `\nsf-releaselens: the extension has outgrown its size budget.\n\n${failures
        .map((line) => `  ${line}`)
        .join('\n')}\n\n` +
        'If the growth is deliberate, raise the limit in the same commit that causes it and say\n' +
        'why: `node scripts/check-size.mjs --update`. If it is not deliberate, something got\n' +
        'shipped that should not have — a dependency, a source map, a vendored library.\n',
    );
    process.exitCode = 1;
    return;
  }

  process.stdout.write('\nsf-releaselens: within the size budget.\n');
}

function report(measured, budget) {
  const line = (label, actual, limit, unit = kb) =>
    `  ${label.padEnd(20)} ${unit(actual).padStart(10)}   budget ${unit(limit).padStart(10)}   ${percent(actual, limit)}\n`;

  process.stdout.write('\n');
  process.stdout.write(line('Packaged zip', measured.zipBytes, budget.limits.zipBytes));
  process.stdout.write(line('Unpacked dist/', measured.unpackedBytes, budget.limits.unpackedBytes));
  process.stdout.write(
    line('Files', measured.fileCount, budget.limits.fileCount, (n) => `${n}`),
  );
  process.stdout.write(
    line('Largest file', measured.largest[0].bytes, budget.limits.largestFileBytes),
  );
  process.stdout.write('\n  Largest shipped files:\n');
  for (const file of measured.largest) {
    process.stdout.write(`    ${kb(file.bytes).padStart(9)}  ${file.path}\n`);
  }
}

function percent(actual, limit) {
  return `${Math.round((actual / limit) * 100)}% of budget`;
}

function roundUpKb(bytes) {
  return Math.ceil(bytes / 1024) * 1024;
}

main().catch((cause) => {
  process.stderr.write(
    `\nsf-releaselens: size check failed: ${cause.message}\n` +
      'Run `npm run build && npm run package` first; this measures the artefacts, not the source.\n',
  );
  process.exitCode = 1;
});
